package View;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class validatedemande extends javax.swing.JFrame implements ActionListener {

        /**
         * Creates new form verifierDemandes
         */
        public validatedemande(int i) {
            initComponents(i);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents(int i) {

            jButton3 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jLabelNbrChambre = new javax.swing.JLabel();
            jButtonaccep = new javax.swing.JButton();
            jButtonref = new javax.swing.JButton();
            jButtonigno = new javax.swing.JButton();

            jButton3.setBackground(new java.awt.Color(0, 51, 153));
            jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jButton3.setForeground(new java.awt.Color(255, 255, 255));
            jButton3.setText("envoyer");

            jButton5.setBackground(new java.awt.Color(0, 51, 153));
            jButton5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jButton5.setForeground(new java.awt.Color(255, 255, 255));
            jButton5.setText("envoyer");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 51, 153));
            jLabel1.setText("traitement de demandes  :");

            jLabelNbrChambre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabelNbrChambre.setForeground(new java.awt.Color(0, 51, 153));
            jLabelNbrChambre.setText("demande "+i+ " :");

            jButtonaccep.setBackground(new java.awt.Color(0, 51, 153));
            jButtonaccep.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jButtonaccep.setForeground(new java.awt.Color(255, 255, 255));
            jButtonaccep.setText("accepter");
            jButtonaccep.addActionListener(this);

            jButtonref.setBackground(new java.awt.Color(0, 51, 153));
            jButtonref.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jButtonref.setForeground(new java.awt.Color(255, 255, 255));
            jButtonref.setText("refuser ");
            jButtonref.addActionListener(this);

            jButtonigno.setBackground(new java.awt.Color(0, 51, 153));
            jButtonigno.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jButtonigno.setForeground(new java.awt.Color(255, 255, 255));
            jButtonigno.setText("ignorer");
            jButtonigno.addActionListener(this);

            setVisible(true);
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabelNbrChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButtonaccep)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(jButtonref)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                    .addComponent(jButtonigno)
                                                    .addGap(40, 40, 40))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel1)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabelNbrChambre)
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButtonaccep)
                                            .addComponent(jButtonref)
                                            .addComponent(jButtonigno))
                                    .addContainerGap(125, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButtonaccep;
        private javax.swing.JButton jButtonigno;
        private javax.swing.JButton jButtonref;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabelNbrChambre;

    @Override
    public void actionPerformed(ActionEvent e) {
        if ((inter.i)>=inter.hotel.demandes.size())
        {
            admin interfaceAdministrateur=new admin();
            this.dispose();
        }
        else {
            inter.i++;
            if (inter.administrateur.Verifier_Disponibilite(inter.hotel.demandes.get(inter.i))==-1)
            {
               guinovalid interfaceDemandesNonValides=new guinovalid(inter.i);
               this.dispose();
            }
            else {
                validatedemande interfaceDemandesValides=new validatedemande(inter.i);
                this.dispose();
            }
        }
    }
    // End of variables declaration//GEN-END:variables
    }

